image:
  file: .gitpod.Dockerfile

tasks:
  - init: sdk use java 16.0.1.hs-adpt
    command: cd script; mvn compile install
  - init: sdk use java 16.0.1.hs-adpt
    command: cd script; mvn clean install -DskipUiTests -DskipTests; cd springboot/server; mvn spring-boot:run

ports:
  # used by virtual desktop and vnc, supports JavaFX
  - port: 6080
  - port: 8080

vscode:
  extensions:
    - vscjava.vscode-java-pack
