@startuml ComponentDiagram

component script.core {
	package core.main #EDDBC0
}

component jackson #LightCoral {
}

component gson #LightCoral {

}

component script.ui{
	package ui #EDDBC0
}

component javafx {
	component fxml #LightCoral {
	}
}

component script.data {
	package data #EDDBC0
}

component script.springboot.server {
  package springboot.server #EDDBC0
}

component spring #LightCoral {
}

script.ui .left.> javafx
script.ui .> fxml
script.ui .> core.main

ui ...> data

core.main ..> jackson

data ..> jackson
data ..> gson
data .left.> core.main

script.springboot.server .> spring
script.springboot.server ..> jackson

springboot.server ...> data

@enduml